### ISSUE TITLE
Uncaught ReferenceError: module is not defined at big-text.js:243

### ISSUE THREAD

**Issue by ScottBeeson** [BrOrlandi/bigtext.js#2]
All I did was add the script to my index.html file, I haven't even invoked it yet.  Looks like this is dependent upon react or something?

**Comment by BrOrlandi** [comment]
Yes, it depends on a module manager, I recommend you install it via NPM and use Webpack to manage your dependencies. It does not depend on react.

**Comment by dlidstrom** [comment]
It's nice to not *have* to depend on a module manager. Whoever has the same problem, add this before including this script:

```javascript
window.module = {};
```

**Comment by Jetroid** [comment]
See #5
